The array or Array keyword can be used as validator to check if an input argument is a numpy ndarray

In [3]:
from vpfargs import validate, array
import numpy as np

In [6]:
@validate(array)
def foo(x):
    print(x)

foo(np.ones([2,2]))
try:
    foo([1,2,3])
except Exception as e:
    print(e)

[[1. 1.]
 [1. 1.]]
Invalid argument at position 1: Type ndarray expected but got list


array keyword is an alias of np.ndarray when used as a validator. The code above could be also written as...

In [7]:
@validate(np.ndarray)
def foo(x):
    print(x)

foo(np.ones([2,2]))
try:
    foo([1,2,3])
except Exception as e:
    print(e)

[[1. 1.]
 [1. 1.]]
Invalid argument at position 1: Type ndarray expected but got list


But array can specify filters so that only numpy arrays with specific properties match the validator

In [14]:
@validate(array(dtype=np.uint32, shape=(3,3)))
def foo(x):
    print(x)

foo(np.ones([3,3], dtype=np.uint32))

try:
    foo(np.zeros([3,3], dtype=np.float64))
except Exception as e:
    print(e)
    
try:
    foo(np.ones([4,4], dtype=np.uint32))
except Exception as e:
    print(e)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
Invalid argument at position 1: Expected ndarray uint32 dtype but got float64
Invalid argument at position 1: Expected 3x3 array but got 4x4 array


In the last example, only arrays with a 3x3 shape an uint32 elements are matched
